---

marp: true
size: 16:9
paginate: true
footer: (c) 2021 Gorka Prieto
style: |
    section {font-size: 18pt}
    section::before {content: "Tema 8: Excepciones"};

---

Programación en Entornos Distribuidos{.h1}

Tema 8: Excepciones{.h2}

<br/>

{.line}

<br/>

2º Ingeniería en Tecnología de Telecomunicación (UPV/EHU){.s3}

Curso 2020/2021{.s3}

---

Licencia de uso{.h1}

©2019-2021, Gorka Prieto Agujeta <<gorka.prieto@ehu.eus>>

Este documento está derivado de documentos anteriores desarrollados por Jose Daniel Gutiérrez Porset, Gaizka Abaroa Erkoreka y Javier del Ser Lorente.

Se otorga permiso para copiar, distribuir y/o modificar este documento bajo los términos de la Licencia de Documentación Libre de GNU en su versión 1.2 o cualquier otra versión posterior publicada por la Free Software Foundation, siendo todo él invariante. Una copia de la licencia está disponible en la web de la Free Software Foundation, dentro de la sección titulada GNU Free Documentation License.

[yes]: figs/yes.png
[no]: figs/no.png

---

Índice{.h1}

:::columns
@[toc]
:::

---

<style scoped>
    code {font-size: 14pt;}
</style>

# Introducción

- Las situaciones de **error** son inevitables en la ejecución de un programa, la cuestión es ¿cómo las gestionamos?
- Considera el siguiente pseudocódigo:
    :::columns
    ```shell
    leerFichero() {
        abrirFichero()
        calcularTamaño()
        reservarMemoria()
        leerFicheroMemoria()
        cerrarFichero()
    }
    ```
    - ¿Qué sucede si no se puede abrir el fichero?, ¿y si no se puede determinar su tamaño?, ¿y si no hay suficiente memoria libre?, ¿y si la lectura falla?, ¿y si no se puede cerrar el fichero?
    :::
- Una opción sería emplear sentencias `if-then-else`:
    :::columns
    ```shell
    leerFichero() {
        if !abrirFichero()
            manejarErrorAbrir()
        else if !calcularTamaño()
            manejarErrorTamaño()
        else if !reservarMemoria()
            ...
    }
    ```
    - Mucho código engorroso para comprobar y gestionar errores
    - Dificulta la interpretación del flujo normal de trabajo (sin errores)
    :::

---

<style scoped>
    code {font-size: 14pt;}
</style>

- Muchos lenguajes soportan el concepto de **excepción**:    
    - Evento que ocurre durante la ejecución del programa y que **interrumpe** el flujo normal
        - No se ejecuta el resto de código hasta que alguien la **capture**
    - Nos permite gestionar mejor estas situaciones excepcionales de error:
        - **Separar** el manejo de errores del código "normal"
        - **Propagar** los errores sobre la pila de llamadas a funciones (hasta la función raíz)
        - **Diferenciar** y tratar todos los errores de forma personalizada
    :::columns
    ```shell {.break-after}
    leerFichero() {
        try {
            abrirFichero()
            calcularTamaño()
            reservarMemoria()
            leerFicheroMemoria()
            cerrarFichero()
        } catch errorAbrir {
            ...
        } catch errorMemoria {
            ...
        }
    }
    ```
    ```shell
    leerFichero() errorAbrir, errorMemoria, ... {
        try {
            abrirFichero()
            calcularTamaño()
            reservarMemoria()
            leerFicheroMemoria()
            cerrarFichero()
        }
    }
    ```
    :::

---

<style scoped>
    section {
        padding-right: 0px;
        display: block;
    }
</style>

# Jerarquía de clases

- Las excepciones son objetos de tipo **Throwable** (jerarquía de clases)

![rfloat width:560px](https://www.seleniumeasy.com/sites/default/files/pictures/java/ExceptionHierarchy.png)

## Tipos de excepciones

- _Unchecked_ o **implícitas**:
    - No es necesario gestionarlas (`throws`/`catch`)
    - ==No anticipables o no recuperables==
    - `Error`: externos a la app (VM)        
    - `RuntimeException`: internos a la app (bugs)
- _Checked_ o **explícitas**:
    - Obligatorio gestionarlas (`throws`/`catch`)
    - Situaciones a las que el programa debería ==anticiparse y recuperarse==:
        - Ej.: usuario introduce un nombre de fichero equivocado que no existe

:::note
https://docs.oracle.com/javase/tutorial/essential/exceptions/catchOrDeclare.html
:::

---

## Clase Throwable

:::columns
```java {.break-after}
public class Throwable {
    // Constructores sobrecargados
    Throwable();
    Throwable(String message);
    Throwable(String message, Throwable cause);
    Throwable(Throwable cause)

    // Algunos métodos de utilidad
    Throwable getCause();
    String getMessage();
    void printStackTrace();
    void printStackTrace(PrintStream s);
    void printStackTrace(PrintWriter s);
    // ...
}
```
```shell
java.lang.NullPointerException
         at MyClass.mash(MyClass.java:9)
         at MyClass.crunch(MyClass.java:6)
         at MyClass.main(MyClass.java:3)
```
```shell
HighLevelException: MidLevelException: LowLevelException
         at Junk.a(Junk.java:13)
         at Junk.main(Junk.java:4)
 Caused by: MidLevelException: LowLevelException
         at Junk.c(Junk.java:23)
         at Junk.b(Junk.java:17)
         at Junk.a(Junk.java:11)
         ... 1 more
 Caused by: LowLevelException
         at Junk.e(Junk.java:30)
         at Junk.d(Junk.java:27)
         at Junk.c(Junk.java:21)
         ... 3 more
```
:::
:::note
https://docs.oracle.com/javase/8/docs/api/java/lang/Throwable.html
https://docs.oracle.com/javase/8/docs/api/java/lang/Throwable.html#printStackTrace--
:::

---

# Captura

## Sintaxis básica

:::columns
- El código que puede generar excepciones debe encerrarse dentro de un bloque `try{...}`:
    - Se puede generar más de un tipo de excepción
    - Cuando se genera una excepción se salta el resto de instrucciones dentro del `try`
- A continuación, la excepción se captura con bloques `catch() {...}`
```java {.break-before}
try {
    // Código que puede generar
    // excepciones
} catch (ExceptionType1 name) {
    // Tratamiento del primer
    // tipo de excepción
} catch (ExceptionType2 name) {
    // Tratamiento del segundo
    // tipo de excepción
}
```
```java
try {
    // Código que puede generar
    // excepciones
} catch (ExceptionType1|ExceptionType2 ex) {
    // Tratamiento común a ambas excepciones
}
```
:::
:::note
https://docs.oracle.com/javase/tutorial/essential/exceptions/catch.html
:::

---

## Relación de herencia

- La excepción se captura en el **primer** `catch` cuyo tipo es asignable a la excepción:
    - Relación de herencia e interfaces
    - Una vez que se captura en un bloque `catch` ya no se ejecutan el resto
- Se pueden capturar diferentes excepciones empleando una clase base común
- Se deben capturar las excepciones ==más concretas en primer lugar==, y las más generales al final:
    - Si no lo hiciéramos así, habría `bloques` catch en los que no se entraría nunca!

:::columns
![center][yes]
```java {.break-after}
try {
    // Genera excepción
} catch (IOException ex) {
    // Tratamiento IOException
} catch (Exception ex) {
    // Tratamiento del resto de casos
}
```
![center][no]
```java
try {
    // Genera excepción
} catch (Exception ex) {
    // Tratamiento de todos los casos
} catch (IOException ex) {
    // No se ejecutaría NUNCA!!
}
```
:::

---

## Bloque finally

:::columns
- Bloque opcional que se puede incluir después de los bloques `catch`
- Se ejecuta **siempre** tras finalizar el `try`:
    - Si no ocurre excepción, incluso aunque se ponga un `return` en el `try`
    - Si sí ocurre excepción (aunque se capture/propague)
- Útil para liberar recursos en cualquier situación posible

```java
PrintWriter out = null;
try {
    out = new PrintWriter("fichero.txt");
    // ...
} finally {
    if (out != null) { 
        System.out.println("Closing PrintWriter");
        out.close(); 
    } else { 
        System.out.println("PrintWriter not open");
    } 
}
```
:::
:::note
https://docs.oracle.com/javase/tutorial/essential/exceptions/finally.html
:::

---

### Ejemplo con un recurso

:::columns
```java {.break-after}
package eus.ehu.ped;

import java.io.FileNotFoundException;
import java.io.PrintWriter;

public class Excepciones {

    public static void main(String[] args) {
        PrintWriter pw = null;
        int num;

        try {
            pw = new PrintWriter("incrementos.txt");
            for( String arg : args ) {
                num = Integer.parseInt(arg);
                pw.println(num+1);
            }
        } catch (FileNotFoundException ex) {
            System.err.println("Error al crear el fichero");
        } catch (NumberFormatException ex) {
            System.err.println("Error al convertir a número");
        } catch (Exception ex) {
            ex.printStackTrace();
        } finally {
            if( pw != null )
                pw.close();
        }
    }

}
```
Queremos liberar `pw` en todos los casos:
1. En caso de que falle el `new`:
    - Lo inicializamos a `null` para no tratar de cerrarlo en este caso (si no daría un `NullPointerException`)
1. En caso de que funcione el `new` y ocurra alguna excepción que se capture
1. En caso de que ocurra alguna excepción que no se capture
1. En caso de que todo vaya bien y no ocurran excepciones
:::

---

<style scoped>
    pre {font-size: 11pt;}
</style>

### Ejemplo con dos recursos

- Hay que tener en cuenta que el `close()` puede fallar y lanzar una nueva excepción dentro del bloque `finally`, pero hay que seguir cerrando los demás recursos
:::columns
![center][yes]
```java {.break-after}
// try-finally is ugly when used with more than one resource!
static void copy(String src, String dst) throws IOException {
    InputStream in = new FileInputStream(src);
    try {
        OutputStream out = new FileOutputStream(dst);
        try {
            byte[] buf = new byte[BUFFER_SIZE];
            int n;
            while ((n = in.read(buf)) >= 0)
                out.write(buf, 0, n);
        } finally {
            out.close();
        }
    } finally {
        in.close();
    }
}
```

.{.break}

![center][no]

```java
// Si falla in.close() no se ejecutará out.close()
static void copy(String src, String dst) throws IOException {
    InputStream in = new FileInputStream(src);
    OutputStream out = null;
    try {
        out = new FileOutputStream(dst);
        byte[] buf = new byte[BUFFER_SIZE];
        int n;
        while ((n = in.read(buf)) >= 0)
            out.write(buf, 0, n);
    } finally {
        in.close();        
        if (out != null)
            out.close();
    }
}
```
:::
:::note
Joshua Bloch, “Effective Java”. Third Edition, 2018.
:::

---

## Try con recursos

### Introducción

:::columns
- **Recurso**: objeto que debe ser cerrado antes de olvidarse de él:
    - Ejemplo: ficheros, sockets, etc.
- _try-con-recursos_:
    - Una ampliación al `try` normal
    - Se encarga de que todos los recursos sean **cerrados automáticamente**
- Deben implementar la interfaz `java.lang.AutoCloseable`:
    - `java.lang.Closeable` la extiende
    - Método `close()`
- Los recursos se declaran dentro de `try()` y ya no que cerrarlos explícitamente:
    ```java
    try (
        Tipo1 recurso1 = new Tipo1();
        Tipo2 recurso2 = new Tipo2();
    ) {
        // Trabajar con los recursos
    }
    ```
- **Orden** de cierre contrario al de declaración
- **Preferir** _try-con-recursos_ frente a _try-finally_:
    - Sintaxis más compacta
    - Excepciones suprimidas
:::
:::note
https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html
:::

---

### Ejemplo de try-con-recursos

```java
package eus.ehu.ped;

import java.io.FileNotFoundException;
import java.io.PrintWriter;

public class Recursos {
    public static void main(String[] args) {
        int num;

        try (
            PrintWriter pw1 = new PrintWriter("numeros.txt");
            PrintWriter pw2 = new PrintWriter("incrementos.txt");
        ){
            for( String arg : args ) {
                num = Integer.parseInt(arg);
                pw1.println(num);
                pw2.println(num+1);
            }
        } catch (FileNotFoundException ex) {
            System.err.println("Error al crear el fichero");
        } catch (NumberFormatException ex) {
            System.err.println("Error al convertir a número");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
```

---

### Excepciones suprimidas

- Si se producen varias excepciones (ej. en el `try` y al hacer los `close()` automáticos):
    - Sólo se lanza la **primera**, el resto quedan "suprimidas"
    - Las excepciones suprimidas se pueden recuperar si interesan
- En el finally sólo se mostraba la última (la menos interesante), y ¡se perdía la del `try`!

### Recursos creados en otro lugar

- ¿Y si los recursos se han creado en otro lugar? (ej. métodos `open()` y `close()`)
    - Se pueden cerrar con un **_try-con-recursos_ vacío**!

:::columns
```java
@Override
public void open() throws IOException {
    socket = ...;
    dis = new DataInputStream(
        socket.getInputStream());
    dos = new DataOutputStream(
        socket.getOutputStream());
}
```
```java {.break-before}
@Override
public void close() throws IOException {
    try (
        Socket s = socket;
        DataInputStream dis = this.dis;
        DataOutputStream dos = this.dos;) {
    }
}
```
:::

---

<style scoped>
    pre {font-size: 11pt;}
</style>

### Utilizar recurso propio

:::columns
```java
public interface AutoCloseable {
    void close() throws Exception;
}

public interface Closeable extends AutoCloseable {
    void close() throws IOException;
}
```

```java
public class MiRecurso implements Closeable {
    private final int id;

    public MiRecurso(int id) {
        this.id = id;
    }
        
    public void open() {
        System.out.println("Abierto #" + id);
    }
    
    public void work() {
        System.out.println("Trabajando #" + id);
    }

    @Override
    public void close() throws IOException {
        System.out.println("Cerrado #" + id);
    }    
}
```

```java {.break-before}
public class Aplicacion {
    public static void main(String[] args) {
        try(
            MiRecurso recurso1 = new MiRecurso(1);
            MiRecurso recurso2 = new MiRecurso(2);
        ) {
            recurso1.open();
            recurso2.open();
            recurso1.work();
            recurso2.work();
        } catch (IOException ex) {
            System.err.println(ex.getMessage());
        }
    }
    
}
```

```shell
Abierto #1
Abierto #2
Trabajando #1
Trabajando #2
Cerrado #2
Cerrado #1
```
:::

---

# Lanzamiento

- Si una excepción no se captura se propaga hacia el método llamante, para que éste la trate:
    - Si no la trata, se sigue propagando hasta llegar al `main()` en última instancia:
        - Si en el `main()` tampoco se trata, se aborta la ejecución

## Sintaxis

- Si no se captura una excepción explícita, hay que especificar que se lanza (**throws**):
    - En el ==prototipo== del método:
        - Es realmente parte de la interfaz que ese método ofrece
        - Quien lo llame sabe lo que puede ocurrir
    - Se emplea la palabra reservada `throws` seguida por la lista de excepciones que se pueden lanzar separadas por coma (se pueden resumir en clase base común)
- Podemos lanzar una excepción manualmente (**throw**):
    - Mediante la palabra reservada `throw` seguida por un objeto `Throwable`
    - Si no la capturamos tendremos que incluirla también en el `throws`

---

## Ejemplo

```java
public class Factorial {
    public static void main(String[] args) {
        try {
            if( args.length != 1 )
                throw new Exception("Debes indicar un número"); // Puedo lanzar y capturar en el mismo método
            int fact = factorial(args[0]);
            System.out.println(fact);
        } catch (Exception e) {
            System.err.println(e.getMessage());
            e.printStackTrace();
        }
    }

    private static int factorial(String arg) throws Exception { // Explícita, la tengo que poner en el throws
        try {
            int num = Integer.parseInt(arg);
            int fact = factorial(num);
            return fact;
        } catch (NumberFormatException e) {
            throw new Exception("Debes introducir un número entero");
        }
    }

    private static int factorial(int num) { // Implícita, no pongo el throws
        int fact = 1;
        if( num < 0 )
            throw new IllegalArgumentException("El número debe ser mayor o igual que 0");
        while( num > 0 )
            fact *= num--;
        return fact;
    }
}
```

---

<style scoped>
    pre {font-size: 11pt;}
</style>

# Excepciones propias

## Ejemplo

- Es posible crear nuevas excepciones ampliando la clase `Exception` o una de sus subclases:
    - La nueva clase debe tener al menos un constructor que llame al constructor de la superclase
- La clase `Exception` ofrece distintos constructores que pueden ser referenciados desde las subclases. Los más utilizados son:
    - `public Exception()` : inicializa la excepción con valores de default (mensaje nulo)
    - `public Exception(String mensaje)`: inicializa la excepción con el mensaje recibido como parámetro.

:::columns
```java
public class NumeroNegativoException extends Exception {
    private static final long serialVersionUID = 1L;

    public NumeroNegativoException() {
        super("El número debe ser mayor o igual que 0");
    }
}
```
```java {.break-before}
public class Factorial {
    // Como en el ejemplo anterior ...

    private static int factorial(int num)
            throws NumeroNegativoException {
        int fact = 1;
        if (num < 0)
            throw new NumeroNegativoException();
        while (num > 0)
            fact *= num--;
        return fact;
    }
}
```
:::

---

## Herencia de excepciones

- Si en una subclase se **redefinen** métodos que en la superclase lanzan excepciones explícitas:
    - ==No se podrán indicar nuevas excepciones== explícitas que no estén declaradas con `throws` en el método de la superclase:
        - Excepción: se pueden indicar nuevas excepciones explícitas que sean descendientes de las excepciones declaradas en el método de la superclase.
    - Sí podrán indicarse menos.
- No aplica para los constructores, pues no se heredan.
- Como **previsión** para subclases:
    - En un método de una clase se puede indicar un número suficiente de excepciones explícitas para que, aunque en dicho método no sean lanzadas, sí puedan incluirse en la declaración de los métodos reescritos de clases derivadas.

---

# Recomendaciones

- **Separar** la lógica del programa y el código de tratamiento de error mediante gestores de excepciones.
- Lanzar las menos excepciones posibles, y preferentemente que sean explícitas.
- Tratamiento:
    - No dejar bloques catch con cuerpo vacío.
    - No atrapar excepciones `java.lang.Error` porque son propias de la JVM y pueden implicar estados inconsistentes.
    - Propagar lo menos posible las excepciones, intentando **tratarlas cuanto antes**.
        - Hacer un `catch ... printStackTrace()` y seguir trabajando como si no hubiese ocurrido el error no es tratar una excepción.
    - Usar **_try-con-recursos_** para liberar recursos (ej. cierre de ficheros)